GET http://localhost:3001/users

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "email": "viggo@gmail.com",
    "password": "viggo2018",
    "admin": "0"
}

###

GET http://localhost:3001/movies

###

POST http://localhost:3001/movies
Content-Type: application/json

{
    "title": "Blade Runner",
    "year": "1982",
    "director": "Ridley Scott",
    "imageurl": "blade-runner.png"
}

###

GET http://localhost:3001/favorites/3

###

POST http://localhost:3001/favorites
Content-Type: application/json

{
    "id_user": 3,
    "id_movie": 2
}